version: V8-{branch}.{build}

os: Visual Studio 2017

clone_folder: C:\projects
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:

environment:

  matrix:
    - v8_platform:  "x64"
      v8_vstudio:   "VS2017"
      v8_vcversion: "vc15"
      v8_toolset:   "v141"
      v8_branch:    "7.2-lkgr"

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat" %v8_platform%
  - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\afxwin*.h" /s
  - set include=%include%;"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\include"
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - set PATH=C:\projects\depot_tools;%PATH%
  - cd C:\projects\depot_tools
  - fetch V8

build_script:
  - cd \projects\depot_tools\v8
  - set PATH=C:\projects\depot_tools\v8;%PATH%
  - set GYP_MSVS_VERSION=2017
  - set VC=15
  - set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - set GYP_CHROMIUM_NO_ACTION=0
  - call git fetch origin %v8_branch%
  - call git pull --depth 1
  - call git checkout %v8_branch%
  - call gclient sync
  - call gn gen %v8_branch%\%v8_platform%.release --args="is_component_build=true is_debug=false v8_use_snapshot=false target_cpu=\"%v8_platform%\"" --ide=vs
  - cd %v8_branch%\%v8_platform%.release
  - msbuild all.sln
  - dir *.exe *.dll *.lib

test: off
