version: V8-{branch}.{build}

os: Visual Studio 2017

clone_folder: C:\projects
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:

environment:

  matrix:
    - v8_platform:  "x64"
      v8_vstudio:   "VS2017"
      v8_vcversion: "vc15"
      v8_toolset:   "v141"
      v8_branch:    "lkgr"

install:
  - set platform=%v8_platform%
  - cd C:\projects
  - curl -k -fSL -o depot_tools.7z https://phpdev.toolsforresearch.com/depot_tools.7z
  - if exist depot_tools rd depot_tools /s /q
  - 7z.exe x depot_tools.7z

build_script:
  - cd \projects\depot_tools\v8
  - set PATH=C:\projects\depot_tools;C:\projects\depot_tools\v8;%PATH%
  - set GYP_MSVS_VERSION=2017
  - set VC=15
  - set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - set GYP_CHROMIUM_NO_ACTION=0
  - call git fetch origin %v8_branch%
  - call git checkout %v8_branch%
  - rem call git pull --depth 1
  - rem call gclient sync
  - rem call gn gen %v8_branch%\%v8_platform%.release --args="is_component_build=true is_debug=false v8_use_snapshot=false target_cpu=\"%v8_platform%\"" --ide=vs
  - type %v8_branch%\%v8_platform%.release\args.gn
  - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\afxwin*.h" /s
  - set include=%include%;"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\include"
  - rem ninja -C %v8_branch%\%v8_platform%.release
  - cd C:\projects\depot_tools\v8\%v8_branch%\%v8_platform%.release
  - dir *.exe *.dll *.lib

test_script:
  - cd C:\projects\depot_tools\v8\%v8_branch%\%v8_platform%.release
  - unittests.exe
