version: V8-{branch}.{build}

os: Visual Studio 2017

clone_folder: C:\projects
shallow_clone: true

skip_tags: true

matrix:
  fast_finish: true

cache:

environment:

  matrix:
    - v8_platform:  "x64"
      v8_vstudio:   "VS2017"
      v8_vcversion: "vc15"
      v8_toolset:   "v141"
      v8_branch:    "lkgr"

install:
  - set platform=%v8_platform%
  - set PATH=C:\projects\depot_tools;C:\projects\depot_tools\v8;%PATH%
  - set GYP_MSVS_VERSION=2017
  - set VC=15
  - set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - set GYP_CHROMIUM_NO_ACTION=0
  - cd C:\projects
  - rem git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - rem cd C:\projects\depot_tools
  - rem call fetch V8
  - rem cd C:\projects\depot_tools\v8
  - rem call git fetch origin master
  - rem call git checkout master
  - rem call git pull
  - rem call gclient sync
  - rem previous lines moved to install.bat to circumvent Appveyor time limit of 59:59m
  - curl -k -fSL -o depot_tools.7z https://phpdev.toolsforresearch.com/depot_tools.7z
  - if exist depot_tools rd depot_tools /s /q
  - 7z.exe x depot_tools.7z

artifacts:
  - path: "%v8_branch%-%v8_platform%-vc%VC%.7z"

build_script:
  - cd C:\projects\depot_tools\v8
  - rem call git fetch origin %v8_branch%
  - rem call git checkout %v8_branch%
  - rem call git pull --depth 1
  - rem call gclient sync
  - rem call gn gen %v8_branch%\%v8_platform%.release --args="is_component_build=true is_debug=false v8_use_snapshot=false target_cpu=\"%v8_platform%\"" --ide=vs
  - rem ninja -C %v8_branch%\%v8_platform%.release
  - rem previous lines moved to build.bat to circumvent Appveyor time limit of 59:59m
  - cd C:\projects\depot_tools\v8\%v8_branch%\%v8_platform%.release
  - if exist api*.dll del api*.dll
  - if exist pgosweep.exe del pgosweep.exe
  - xcopy v8*.lib C:\projects\%v8_branch%-%v8_platform%-vc%VC%\lib\ /y
  - xcopy v8*.dll C:\projects\%v8_branch%-%v8_platform%-vc%VC%\bin\ /y
  - xcopy v8*.dll.pdb C:\projects\%v8_branch%-%v8_platform%-vc%VC%\bin\ /y > nul
  - xcopy icu*.lib C:\projects\%v8_branch%-%v8_platform%-vc%VC%\lib\ /y
  - xcopy icu*.dll C:\projects\%v8_branch%-%v8_platform%-vc%VC%\bin\ /y
  - xcopy icu*.dll.pdb C:\projects\%v8_branch%-%v8_platform%-vc%VC%\bin\ /y > nul
  - xcopy icu*.dat C:\projects\%v8_branch%-%v8_platform%-vc%VC%\bin\ /y > nul
  - xcopy *exe* C:\projects\%v8_branch%-%v8_platform%-vc%VC%\bin\ /y > nul
  - xcopy C:\projects\depot_tools\v8\include\*.h C:\projects\%v8_branch%-%v8_platform%-vc%VC%\include\ /s /y > nul
  - cd C:\projects
  - if exist %v8_branch%-%v8_platform%-vc%VC%.7z del %v8_branch%-%v8_platform%-vc%VC%.7z
  - 7z.exe a %v8_branch%-%v8_platform%-vc%VC%.7z %v8_branch%-%v8_platform%-vc%VC%

test_script:
  - rem cd C:\projects\depot_tools\v8
  - rem call python tools/run-tests.py --progress=verbose --mode Release --outdir %v8_branch%\%v8_platform%.release --buildbot --timeout=200 --random-seed=975877910 bot_default --variants=more,dev --rerun-failures-count=2 --mastername client.v8 --buildername V8 Win64 - msvc --swarming
  - rem previous lines moved to testing.bat
  - cd C:\projects\depot_tools\v8\%v8_branch%\%v8_platform%.release
  - rem failing in 7.1-lkgr (7.1.302.33)
  - cctest.exe test-heap/TestSizeOfObjectsVsHeapIteratorPrecision --random-seed=975877910 --no-turbo-verify-allocation --stress-opt --always-opt --nohard-abort & exit 0
  - rem failing in 7.1-lkgr and lkgr (7.3)
  - cctest.exe test-heap/MapRetaining --random-seed=975877910 --no-turbo-verify-allocation --stress-opt --always-opt --nohard-abort & exit 0
  - inspector-test.exe C:\projects\\projects\test\inspector\protocol-test.js C:\projects\\projects\test\inspector\debugger/step-snapshot.js --random-seed=975877910 --no-turbo-verify-allocation --stress-opt --always-opt --nohard-abort --embed "function c(f, ...args) { return f(...args); }" & exit 0
  - cctest.exe test-external-string-tracker/ExternalString_ExternalBackingStoreSizeIncreasesAfterExternalization --random-seed=975877910 --no-turbo-verify-allocation --stress-incremental-marking --nohard-abort & exit 0
  - unittests.exe & exit 0
  - rem did unittests.exe fail at '11 tests from BytecodeArrayBuilderTest'?

